[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.0"

  [[repos.hooks]]
  id = "ruff"
  args = ["--fix"]
  types_or = ["file"]
  files = "^ghstack$"

  [[repos.hooks]]
  id = "ruff-format"
  types_or = ["file"]
  files = "^ghstack$"
